services:
  client:
    build:
      context: ./client
      target: ${BUILD_TARGET}
      args:
        - NODE_ENV=${NODE_ENV}
        - PORT=${CLIENT_CONTAINER_PORT}
    image: cubepose-client:${NODE_ENV}
    container_name: cubepose-client-${NODE_ENV}
    ports:
      - "${CLIENT_PORT}:${CLIENT_CONTAINER_PORT}"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${CLIENT_CONTAINER_PORT}
    depends_on:
      - server

  server:
    build:
      context: ./server
      target: ${BUILD_TARGET}
      args:
        - NODE_ENV=${NODE_ENV}
        - PORT=${SERVER_CONTAINER_PORT}
    image: cubepose-server:${NODE_ENV}
    container_name: cubepose-server-${NODE_ENV}
    ports:
      - "${SERVER_PORT}:${SERVER_CONTAINER_PORT}"
    volumes:
      - ./server/src:/app/src
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
      - NODE_ENV=${NODE_ENV}
      - PORT=${SERVER_CONTAINER_PORT}